services:
  madr_mongo_database:
    image: mongo:7
    container_name: madr_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env.docker

  madr_mongo_app:
    image: madr_mongo_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - madr_mongo_database
    env_file:
      - .env.docker

volumes:
  mongo_data:
