name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGO_ROOT_USER: ${{ secrets.MONGO_ROOT_USER }}
      MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Copy file repositories
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pipx install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run task test